### ISSUE TITLE
Using SHA to get commit ID produces nonsensical hashes

### ISSUE THREAD

**Issue by mitchellhansen-wyze** [mainmatter/continue-on-error-comment#4]
First of all, thank you so much for creating this workflow. Saved my bacon when I tried to integrate some checks that should "warn" on failure and found out GHA simply does not support that usecase.

I found quite an odd problem when integrating this workflow along with [trigger-workflow-and-wait](https://github.com/convictional/trigger-workflow-and-wait) though.

If the last commit to a branch that I am PR'ing is a regular commit, `github.sha` works just fine. But, if the last commit to the branch was a merge or revert commit, then `github.sha` gives me a nonsensical commit hash

> The actual commit that triggered the workflow, a revert commit
> ![image](https://user-images.githubusercontent.com/82409818/199599084-b9570c94-d5c5-442b-b333-83c48315ab75.png)

> Output from `continue-on-error-comment`
> ![image](https://user-images.githubusercontent.com/82409818/199596957-c8f1f3c3-9675-4806-bd2d-43fac05fddcb.png)

> The hash that it links to
> ![image](https://user-images.githubusercontent.com/82409818/199596877-a2fd72f1-20e2-4437-9318-224f1b32c2e4.png)

I pass this commit hash to my job on the other end of my `trigger-workflow-and-wait`, and I managed to solve it by using `github.event.pull_request.head.sha` instead. But `continue-on-error-comment` still gives me the nonsensical hash when it comments on my PR.

I see that this workflow is using some `context.sha` to determine the hash, I wonder if this is a similar problem?

**Comment by mansona** [comment]
wowza this one is a bit of a odd one alright 🙈 

So first things first, we're not really linking to a particular SHA when adding this comment (or rather we weren't intending to do it). It turns out that if you put any SHA as a plain text in a comment it will turn that into a link 🤷 We didn't see a problem with it so we left it in there.

Doing a little bit of digging it turns out that this sha that it's giving us is the `Last merge commit on the GITHUB_REF branch` for the PR 🙈 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request 

I agree that it's a bit odd so we should probably remove the SHA from the comment 🤔 

Just to give a bit of context, the only reason we have the SHA in there is so that we can delete previous comments when you push a new commit to your branch. We were originally running it with the Run ID from the github action but if you have multiple workflow yaml files running on the same PR then they all interfere with each other (total nightmare).

Would you object to the SHA just being hidden? We need it for our internals but we could put it as a HTML comment `<!-- sha <big-long-sha> -->` and that **should** hide it from the end user. how does that sound?

**Comment by mitchellhansen-wyze** [comment]
> Would you object to the SHA just being hidden? We need it for our internals but we could put it as a HTML comment  and that should hide it from the end user. how does that sound?

That works for my usecase! I was going to add links to the `test-id` anyway to point directly to the remote job that errored, so the hash can be hidden!

Thanks for the quick response! And thanks again for this awesome little library!
